### ISSUE TITLE
Docs for adding source code through project.json

### ISSUE THREAD

**Issue by karann-msft** [NuGet/ProductTracking#82]
https://github.com/NuGet/Home/issues/2262#issuecomment-228500997

**Comment by cwe1ss** [comment]
Are there already any blogs, gists, ... for this to help us get started?

**Comment by leftler** [comment]
This problem also happens with VS 2017 and projects referenced in the new .csproj format. Content files don't get copied when visual studio does a package restore on the .csproj file.
